# .ebextensions/01_flask_setup.config
commands:
  00_remove_old_venv:
    command: "rm -rf /var/app/staging/venv"  # Ensure old virtual environment is removed
  01_create_venv:
    command: "/usr/bin/python3 -m venv /var/app/staging/venv"  # Create new virtual environment
  02_install_requirements:
    command: "/var/app/staging/venv/bin/pip install -r /var/app/staging/requirements.txt"  # Install dependencies in venv
  03_fix_permissions:
    command: "chown -R ec2-user:ec2-user /var/app/staging/venv"  # Fix permission issues

option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: app:app  # Entry point for your Flask app (adjust if needed)

  aws:elasticbeanstalk:environment:proxy:staticfiles:
    /static: static  # Serve static files (adjust if your app uses static files)

container_commands:
  01_migrate_db:
    command: "source /var/app/staging/venv/bin/activate && python /var/app/staging/manage.py db upgrade"  # Optional: Example for database migration

environment:
  PYTHONPATH: /var/app/staging/venv/bin  # Set the PYTHONPATH to the virtual environment
  FLASK_ENV: production  # Adjust environment variables for Flask (optional)

